[build]
  command = "curl -L https://foundry.paradigm.xyz | bash && source ~/.bashrc && export PATH="~/.foundry/bin:${PATH}" && foundrup && yarn run build:ethernaut"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200